name: 推送检验

on:
  push:
    branches:
      - dev-*
      - for/dev-*

jobs:
  build-to-deploy:
    runs-on: macos-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v2

      - name: 缓存Node.js模块
        uses: actions/cache@v3
        with:
           path: |
              frontend/node_modules
           key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json', 'frontend/yarn.lock') }}
           restore-keys: |
              ${{ runner.os }}-node-

      - name: 设置nodejs版本
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 构建前端
        run: |
          yarn --cwd frontend install --ignore-engines
          yarn --cwd frontend build

      - name: 缓存Go模块
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 设置go版本
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: 构建二进制
        run: |
          go build